version: '3.2'

services:
    webinterface:
        image: ghcr.io/lingo-db/webinterface:latest
        volumes:
            - type: bind
              source: './data'
              target: '/data'
        networks:
            default:
                ipv4_address: '172.20.21.2'
        restart: 'unless-stopped'
        expose:
            - '80/tcp'
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
networks:
    default:
        driver: bridge
        driver_opts:
            ip_range: '172.20.21.0/24'
            'com.docker.network.bridge.enable_icc': 'false'
        ipam:
            driver: default
            config:
                - subnet: '172.20.21.0/24'
